### ISSUE TITLE
Unable to push to babel

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/babel#21]
After changing a string in a sim and running `grunt update`, I tried to push the resulting babel change. See https://github.com/phetsims/chipper/issues/1369. But pre-commit hooks are failing in this repo with 

```
$ git commit -m "push to babel after updating strings"
0 errors in 37459ms


[........................................] 100.00%

Error in fulfilling chunk Promise: [Error: Error: Assertion failed: validation failed:
 value should have typeof boolean, value=undefined
 prunedValidator:
 [object Object]
    at window.assertions.assertFunction (http://localhost:63653/assert/js/assert.js:28:13)
    at validate (http://localhost:63653/chipper/dist/js/axon/js/validate.js:23:17)
    at StateSchema.checkStateObjectValid (http://localhost:63653/chipper/dist/js/tandem/js/types/StateSchema.js:154:9)
    at IOType.isStateObjectValid (http://localhost:63653/chipper/dist/js/tandem/js/types/IOType.js:236:43)
    at IOType.validateStateObject (http://localhost:63653/chipper/dist/js/tandem/js/types/IOType.js:273:10)
    at http://localhost:63653/chipper/dist/js/tandem/js/types/StateSchema.js:143:28
    at Array.forEach (<anonymous>)
    at checkLevel (http://localhost:63653/chipper/dist/js/tandem/js/types/StateSchema.js:137:61)
    at StateSchema.checkStateObjectValid (http://localhost:63653/chipper/dist/js/tandem/js/types/StateSchema.js:147:7)
    at IOType.isStateObjectValid (http://localhost:63653/chipper/dist/js/tandem/js/types/IOType.js:236:43)]
C:\Users\Jesse\Documents\Development\phetsims\chipper\js\phet-io\phetioCompareAPIs.js:128
    return !api.hasOwnProperty( 'version' );
                ^

TypeError: Cannot read properties of undefined (reading 'hasOwnProperty')
    at isOldAPIVersion (C:\Users\Jesse\Documents\Development\phetsims\chipper\js\phet-io\phetioCompareAPIs.js:128:17)
    at _phetioCompareAPIs (C:\Users\Jesse\Documents\Development\phetsims\chipper\js\phet-io\phetioCompareAPIs.js:146:10)
    at C:\Users\Jesse\Documents\Development\phetsims\chipper\js\phet-io\phetioCompareAPISets.js:32:28
    at Array.forEach (<anonymous>)
    at module.exports (C:\Users\Jesse\Documents\Development\phetsims\chipper\js\phet-io\phetioCompareAPISets.js:23:9)
    at C:\Users\Jesse\Documents\Development\phetsims\chipper\js\scripts\hook-pre-commit-task.js:168:53
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async C:\Users\Jesse\Documents\Development\phetsims\chipper\js\scripts\hook-pre-commit-task.js:148:25

Node.js v18.12.0

```

I think @samreid led https://github.com/phetsims/chipper/issues/1369 so assigning to him to start.

**Comment by samreid** [comment]
Is this just changing an English string value, or changing a key, or adding a key?

**Comment by jessegreenberg** [comment]
The key was deleted.

**Comment by samreid** [comment]
I wonder if API files need to be regenerated?  Can you please try running `grunt generate-phet-io-api --stable` from any sim repo?

**Comment by jessegreenberg** [comment]
I ran `grunt generate-phet-io-api --stable` in the quadrilateral repo and saw what appears to be the same error:
```
$ grunt generate-phet-io-api --stable
Running "generate-phet-io-api" task
[                                        ] 0.00%Message from sim: an attempt was made to set the output level for a sound category on an uninitialized sound manager, ignoring
Message from sim: an attempt was made to set the output level for a sound category on an uninitialized sound manager, ignoring
[.............                           ] 33.33%Message from sim: Assertion failed:  validation failed: value should have typeof boolean, value=undefined prunedValidator: JSHandle@object
Error in fulfilling chunk Promise: [Error: Error: Assertion failed: validation failed:
 value should have typeof boolean, value=undefined
 prunedValidator:
 [object Object]
    at window.assertions.assertFunction (http://localhost:63989/assert/js/assert.js:28:13)
    at validate (http://localhost:63989/chipper/dist/js/axon/js/validate.js:23:17)
    at StateSchema.checkStateObjectValid (http://localhost:63989/chipper/dist/js/tandem/js/types/StateSchema.js:154:9)
    at IOType.isStateObjectValid (http://localhost:63989/chipper/dist/js/tandem/js/types/IOType.js:236:43)
    at IOType.validateStateObject (http://localhost:63989/chipper/dist/js/tandem/js/types/IOType.js:273:10)
    at http://localhost:63989/chipper/dist/js/tandem/js/types/StateSchema.js:143:28
    at Array.forEach (<anonymous>)
    at checkLevel (http://localhost:63989/chipper/dist/js/tandem/js/types/StateSchema.js:137:61)
    at StateSchema.checkStateObjectValid (http://localhost:63989/chipper/dist/js/tandem/js/types/StateSchema.js:147:7)
    at IOType.isStateObjectValid (http://localhost:63989/chipper/dist/js/tandem/js/types/IOType.js:236:43)]
[...........................             ] 66.67%Message from sim: Canvas2D: Multiple readback operations using getImageData are faster with the willReadFrequently attribute set to true. See: https://html.spec.whatwg.org/multipage/canvas.html#concept-canvas-will-read-frequently
[........................................] 100.00%
Fatal error: Perennial task failed:
AssertionError [ERR_ASSERTION]: api expected
    at module.exports (C:\Users\Jesse\Documents\Development\phetsims\chipper\js\phet-io\formatPhetioAPI.js:41:3)
    at C:\Users\Jesse\Documents\Development\phetsims\chipper\js\grunt\Gruntfile.js:641:37
    at Array.forEach (<anonymous>)
    at C:\Users\Jesse\Documents\Development\phetsims\chipper\js\grunt\Gruntfile.js:631:12
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async wrap (C:\Users\Jesse\Documents\Development\phetsims\chipper\js\grunt\Gruntfile.js:65:7)
Full Error details:
AssertionError [ERR_ASSERTION]: api expected

```

Then followed up with a commit attempt in babel and saw the error again.

**Comment by samreid** [comment]
I'm not sure I can reproduce this problem.  I tried:

1. Delete this from quadrilateral_strings_en.json:

<details>

```diff
Subject: [PATCH] test
---
Index: quadrilateral-strings_en.json
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/quadrilateral-strings_en.json b/quadrilateral-strings_en.json
--- a/quadrilateral-strings_en.json	(revision f6ecf010b1abd66d31960542b4f83c27702e711d)
+++ b/quadrilateral-strings_en.json	(date 1677437076001)
@@ -104,9 +104,6 @@
   "preferencesDialog.playSoundsForever": {
     "value": "Play Shape Sounds forever when checked in sim."
   },
-  "smallSteps": {
-    "value": "Small Steps"
-  },
   "a11y": {
     "screenSummary": {
       "playAreaDescription": {
Index: js/quadrilateral/view/SmallStepsLockToggleButton.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/quadrilateral/view/SmallStepsLockToggleButton.ts b/js/quadrilateral/view/SmallStepsLockToggleButton.ts
--- a/js/quadrilateral/view/SmallStepsLockToggleButton.ts	(revision f6ecf010b1abd66d31960542b4f83c27702e711d)
+++ b/js/quadrilateral/view/SmallStepsLockToggleButton.ts	(date 1677437118412)
@@ -18,7 +18,7 @@
 import QuadrilateralStrings from '../../QuadrilateralStrings.js';
 
 // constants
-const smallStepsString = QuadrilateralStrings.smallSteps;
+const smallStepsString = 'hello';
 const hintResponseString = QuadrilateralStrings.a11y.voicing.minorIntervalsToggle.hintResponse;
 const lockedNameResponseString = QuadrilateralStrings.a11y.voicing.minorIntervalsToggle.lockedNameResponse;
 const unlockedNameResponseString = QuadrilateralStrings.a11y.voicing.minorIntervalsToggle.unlockedNameResponse;
Index: js/QuadrilateralStrings.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/QuadrilateralStrings.ts b/js/QuadrilateralStrings.ts
--- a/js/QuadrilateralStrings.ts	(revision f6ecf010b1abd66d31960542b4f83c27702e711d)
+++ b/js/QuadrilateralStrings.ts	(date 1677437086120)
@@ -87,8 +87,6 @@
     'playSoundsForever': string;
     'playSoundsForeverStringProperty': LinkableProperty<string>;
   };
-  'smallSteps': string;
-  'smallStepsStringProperty': LinkableProperty<string>;
   'a11y': {
     'screenSummary': {
       'playAreaDescription': string;

```

</details>

(2) Run `grunt update` in quadrilateral
(3) cd to `babel` and run the precommit hooks: `node ../chipper/js/scripts/hook-pre-commit.js --console`

I don't see an error.


```
Linting passed with results.length: 0

QUnit: no problems detected

0 errors in 10688ms

tsc passed

[........................................] 100.00%

All tasks succeeded
```

Am I testing this correctly?

**Comment by jessegreenberg** [comment]
Thanks for testing - very strange. I just:
1) Pulled all repos and restarted transpiler. (no changes detected)
2) Applied your patch and restarted transpiler.
3) Ran `grunt update` in quadrilateral
4) cd to babel and ran hook-pre-commit.js. Here is the output:
```
$ node ../chipper/js/scripts/hook-pre-commit.js --console
Linting passed with results.length: 0

QUnit: no problems detected

0 errors in 30059ms

tsc passed

[........................................] 100.00%

Error in fulfilling chunk Promise: [Error: Error: Assertion failed: validation failed:
 value should have typeof boolean, value=undefined
 prunedValidator:
 [object Object]
    at window.assertions.assertFunction (http://localhost:51084/assert/js/assert.js:28:13)
    at validate (http://localhost:51084/chipper/dist/js/axon/js/validate.js:23:17)
    at StateSchema.checkStateObjectValid (http://localhost:51084/chipper/dist/js/tandem/js/types/StateSchema.js:154:9)
    at IOType.isStateObjectValid (http://localhost:51084/chipper/dist/js/tandem/js/types/IOType.js:236:43)
    at IOType.validateStateObject (http://localhost:51084/chipper/dist/js/tandem/js/types/IOType.js:273:10)
    at http://localhost:51084/chipper/dist/js/tandem/js/types/StateSchema.js:143:28
    at Array.forEach (<anonymous>)
    at checkLevel (http://localhost:51084/chipper/dist/js/tandem/js/types/StateSchema.js:137:61)
    at StateSchema.checkStateObjectValid (http://localhost:51084/chipper/dist/js/tandem/js/types/StateSchema.js:147:7)
    at IOType.isStateObjectValid (http://localhost:51084/chipper/dist/js/tandem/js/types/IOType.js:236:43)]
C:\Users\Jesse\Documents\Development\phetsims\chipper\js\phet-io\phetioCompareAPIs.js:128
    return !api.hasOwnProperty( 'version' );
                ^

TypeError: Cannot read properties of undefined (reading 'hasOwnProperty')
    at isOldAPIVersion (C:\Users\Jesse\Documents\Development\phetsims\chipper\js\phet-io\phetioCompareAPIs.js:128:17)
    at _phetioCompareAPIs (C:\Users\Jesse\Documents\Development\phetsims\chipper\js\phet-io\phetioCompareAPIs.js:146:10)
    at C:\Users\Jesse\Documents\Development\phetsims\chipper\js\phet-io\phetioCompareAPISets.js:32:28
    at Array.forEach (<anonymous>)
    at module.exports (C:\Users\Jesse\Documents\Development\phetsims\chipper\js\phet-io\phetioCompareAPISets.js:23:9)
    at C:\Users\Jesse\Documents\Development\phetsims\chipper\js\scripts\hook-pre-commit-task.js:168:53
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async C:\Users\Jesse\Documents\Development\phetsims\chipper\js\scripts\hook-pre-commit-task.js:148:25

Node.js v18.12.0
```

**Comment by jessegreenberg** [comment]
Changes are still being automatically committed successfully, see https://github.com/phetsims/babel/commit/eba35f57f12ff8acde43cf8e420aadc839bb170c (it includes the change I was trying to make myself).

**Comment by jessegreenberg** [comment]
The failure comes from the PhET-iO API comparison task so I tried running my alias for checking all APIs: `perennial/bin/for-each.sh phet-io-api-stable grunt compare-phet-io-api`. All passed except for gravity-and-orbits, which failed with the same error.

```
Running "compare-phet-io-api" task
[                                        ] 0.00%Error in fulfilling chunk Promise: [Error: Error: Assertion failed: validation failed:
 value should have typeof boolean, value=undefined
 prunedValidator:
 [object Object]
    at window.assertions.assertFunction (http://localhost:53980/assert/js/assert.js:28:13)
    at validate (http://localhost:53980/chipper/dist/js/axon/js/validate.js:23:17)
    at StateSchema.checkStateObjectValid (http://localhost:53980/chipper/dist/js/tandem/js/types/StateSchema.js:154:9)
    at IOType.isStateObjectValid (http://localhost:53980/chipper/dist/js/tandem/js/types/IOType.js:236:43)
    at IOType.validateStateObject (http://localhost:53980/chipper/dist/js/tandem/js/types/IOType.js:273:10)
    at http://localhost:53980/chipper/dist/js/tandem/js/types/StateSchema.js:143:28
    at Array.forEach (<anonymous>)
    at checkLevel (http://localhost:53980/chipper/dist/js/tandem/js/types/StateSchema.js:137:61)
    at StateSchema.checkStateObjectValid (http://localhost:53980/chipper/dist/js/tandem/js/types/StateSchema.js:147:7)
    at IOType.isStateObjectValid (http://localhost:53980/chipper/dist/js/tandem/js/types/IOType.js:236:43)]
[........................................] 100.00%
Fatal error: Perennial task failed:
TypeError: Cannot read properties of undefined (reading 'hasOwnProperty')
    at isOldAPIVersion (C:\Users\Jesse\Documents\Development\phetsims\chipper\js\phet-io\phetioCompareAPIs.js:128:17)
    at _phetioCompareAPIs (C:\Users\Jesse\Documents\Development\phetsims\chipper\js\phet-io\phetioCompareAPIs.js:146:10)
    at C:\Users\Jesse\Documents\Development\phetsims\chipper\js\phet-io\phetioCompareAPISets.js:32:28
    at Array.forEach (<anonymous>)
    at module.exports (C:\Users\Jesse\Documents\Development\phetsims\chipper\js\phet-io\phetioCompareAPISets.js:23:9)
    at C:\Users\Jesse\Documents\Development\phetsims\chipper\js\grunt\Gruntfile.js:685:57
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async wrap (C:\Users\Jesse\Documents\Development\phetsims\chipper\js\grunt\Gruntfile.js:65:7)
Full Error details:
TypeError: Cannot read properties of undefined (reading 'hasOwnProperty')

```

**Comment by samreid** [comment]
This is the code in StateSchema.ts that is failing:

```ts
    else {
      assert && assert( this.validator, 'validator must be present if not composite' );
      const valueStateObject = stateObject;
      if ( toAssert ) {
        validate( valueStateObject, this.validator! );
      }
```

It would be so nice if we could pass contextual details and a message to `validate` so we can indicate the phetioID.  Before that happens, could a debugger/breakpoint tell us what the problematic boolean is?

**Comment by jessegreenberg** [comment]
After https://github.com/phetsims/babel/issues/21#issuecomment-1447270141 I cd'd into gravity-and-orbits and found that I was still in a 1.6 release branch. Checking out master, the problem went away. So sorry to have wasted your time here @samreid, and thanks for helping out here.

Closing.
